name: "base-env"
channels:
  - conda-forge
  - nodefaults
dependencies:
 - aiohttp
 - aiosignal
 - ansiwrap
 - async-generator
 - async-timeout
 - certifi
 - certipy
 - click
 - conda
 - cycler
 - distlib
 - filelock
 - frozenlist
 - gitdb
 - GitPython
 - ipython
 - ipython-genutils
 - Jinja2
 - joblib
 - kiwisolver
 - matplotlib
 - multidict
 - nbdime
 - numpy
 - pamela
 - pandas
 - papermill
 - patsy
 - pillow
 - platformdirs
 - pycurl
 - PyYAML
 - scikit-learn
 - scipy
 - seaborn
 - simpervisor
 - statsmodels
 - tenacity
 - textwrap3
 - threadpoolctl
 - virtualenv
 - webencodings
 - yarl
# - add packages here
# - one per line
prefix: "/opt/conda"
