name: "base-env"
channels:
  - conda-forge
  - nodefaults
dependencies:
 - aiohttp==3.8.4
 - aiosignal==1.3.1
 - ansiwrap==0.8.4
 - async-generator==1.10
 - async-timeout==4.0.2
 - certifi==2022.9.24
 - certipy==0.1.3
 - click==8.1.3
 - conda==22.9.0
 - cycler==0.12.1
 - distlib==0.3.6
 - filelock==3.12.2
 - frozenlist==1.3.3
 - gitdb==4.0.10
 - GitPython==3.1.31
 - ipython==8.14.0
 - ipython-genutils==0.2.0
 - Jinja2==3.0.3
 - joblib==1.3.2
 - jupyter-resource-usage==0.7.2
 - jupyter-server-mathjax==0.2.6
 - jupyter_server_proxy==4.0.0
 - jupyterlab-git==0.41.0
 - jupyterlab-system-monitor==0.8.0
 - jupyterlab-topbar==0.6.1
 - kiwisolver==1.4.5
 - matplotlib==3.3.1
 - multidict==6.0.4
 - nbdime==3.2.1
 - numpy==1.20.3
 - pamela==1.0.0
 - pandas==1.1.3
 - papermill==2.4.0
 - patsy==0.5.6
 - pillow==10.2.0
 - platformdirs==3.8.0
 - pycurl==7.45.1
 - PyYAML==6.0
 - scikit-learn==0.24.1
 - scipy==1.6.3
 - seaborn==0.11.0
 - simpervisor==1.0.0
 - smmap==5.0.0
 - statsmodels==0.12.1
 - tenacity==8.2.2
 - textwrap3==0.9.2
 - threadpoolctl==3.2.0
 - virtualenv==20.23.1
 - webencodings==0.5.1
 - yarl==1.9.2
# - add packages here
# - one per line
prefix: "/opt/conda"
